--A function that retrieves all rentals handled by a specific employee.
CREATE FUNCTION F_GetRentalsByEmployee(@EMPLOYEE_ID INT)
RETURNS TABLE
AS
RETURN
(SELECT *  FROM RENTAL
WHERE EMPLOYEE_ID = @EMPLOYEE_ID
)

SELECT * FROM F_GetRentalsByEmployee(5)

--A function to calculate the total earnings 
--generated by all rentals handled by a specific employee, 
--considering extras, rental rate, insurance, deposit, and rental days.

ALTER FUNCTION dbo.F_CalculateEmployeeEarnings(@EMPLOYEE_ID INT)
RETURNS DECIMAL(10,2)
AS
BEGIN
DECLARE @TOTAL_EARNINGS DECIMAL(10, 2);

    SELECT 
        @TOTAL_EARNINGS = SUM(
            (C.RENTAL_RATE * DATEDIFF(DAY, R.PICKUP_DATE, R.RETURN_DATE)) 
            + P.INSURANCE_PRICE 
            + P.DEPOSIT 
            + ISNULL(EXTRAS_TOTAL, 0)
        )
    FROM CAR C
    JOIN RENTAL R ON R.CAR_ID = C.CAR_ID
    JOIN PAYMENT P ON P.RENTAL_ID = R.RENTAL_ID
    LEFT JOIN (
        SELECT PE.PAYMENT_ID, SUM(E.PRICE) AS EXTRAS_TOTAL
        FROM PAYMENT_EXTRAS PE
        JOIN EXTRAS E ON E.EXTRA_ID = PE.EXTRA_ID
        GROUP BY PE.PAYMENT_ID
    ) EX ON EX.PAYMENT_ID = P.PAYMENT_ID
    WHERE R.EMPLOYEE_ID = @EMPLOYEE_ID

    RETURN ISNULL(@TOTAL_EARNINGS, 0)
END

SELECT DBO.F_CalculateEmployeeEarnings(1)  TOTAL_EARNINGS

